config/routes.rb
JerkTest::Application.routes.draw do

  resources :menu_links


  root to: 'blogs#index'

  get 'admin' => 'admin#index'
  get 'contact' => 'static#contact'
  get 'test' => 'static#test'

  get 'pl' => 'pricelist#index'

  resources :users, :blogs, :blog_images
  
  resources :media, except: :show

  resources :artworks do
    collection{ post :sort }
  end

  resources :categories do
    collection{ post :sort }
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :category
 
  attr_accessible :img_url, :length, :medium, :title, :width, :year, :category_id, :sold, :price
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessible :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  validates :title, :medium, :img_url, :category_id, presence: true

  mount_uploader :img_url, UpjerkUploader

  def crop_avatar
    img_url.recreate_versions! if crop_x.present?
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  scope :descposted, order("blogs.posted DESC")


  attr_accessible :image, :post, :title, :posted

  validates :title, :image, presence: true

  belongs_to :user

  mount_uploader :image, UpjerkblogUploader
  
  self.per_page = 5

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :hidden, :name

  validates :name, presence: true

  has_many :artworks

  before_destroy :ensure_category_has_no_artwork

  private
  
  def ensure_category_has_no_artwork
  	if artworks.empty?
  		return true 
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end
  end

end

app/models/medium.rb
class Medium < ActiveRecord::Base
  attr_accessible :name
end

app/models/menu_link.rb
class MenuLink < ActiveRecord::Base
  attr_accessible :title, :url, :show
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  
  validates :name, presence: true, uniqueness: true
  
  has_secure_password
  
  has_many :blogs
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]

  def index
    @blogs = Blog.descposted.page(params[:page])
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.js { render nothing: true }
    end
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def index
    @media = Medium.all
  end

  def new
    @medium = Medium.new
  end

  def edit
    @medium = Medium.find(params[:id])
  end

  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to media_url, notice: 'Medium was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url }
      format.js { render nothing: true}
    end
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  skip_before_filter :authorize
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created." }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully updated." }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.js { render nothing: true }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    "current" if current_page?(path)
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/menu_links_helper.rb
module MenuLinksHelper
end

app/helpers/pricelist_helper.rb
module PricelistHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.haml
%article.post
  %header
    %h1= link_to blog.title, blog
    %h2= blog.posted
  %img{ src: blog.image_url(:large).to_s, alt: blog.title }
  .post= simple_format blog.post
  %footer
    // .fb-like{ data: { href: blog_url(blog.id), send: 'false', layout: 'button_count', font: 'lucida grande', colorscheme: 'dark' } }
    - if session[:user_id]
      %ul#admin-blog
        %li= link_to 'Edit', edit_blog_path(blog)
        %li= link_to 'Destroy', blog, method: :delete, class: 'delete_btn', data: { confirm: 'Are you sure?' }

app/views/blogs/_form.html.haml
= form_for(@blog) do |f|
  - if @blog.errors.any?
    .error_explanation
      %h2
        = pluralize(@blog.errors.count, "error")
        prohibited this blog from being saved:
      %ul
        - @blog.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label :image
    = f.file_field :image
  .field
    = f.label :title
    = f.text_field :title 
  .field
    = f.label :posted
    = f.date_select :posted
  .field
    = f.label :post
    = f.text_area :post
  .actions
    = f.submit

app/views/blogs/edit.html.haml
%section.admin
  %h1 edit blog entry
  = render 'form'

app/views/blogs/index.html.haml
.posts
  =render partial: "blogs/blog", :collection => @blogs

= will_paginate @blogs

#fb-root
:javascript
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/blogs/index.js.haml
$('.posts').append('<div id="page_#{ @blogs.current_page }"> #{ j render(@blogs) } </div>');
- if @blogs.next_page
  $('.pagination').replaceWith('#{ j will_paginate(@blogs) }');
- else
  $('.pagination').remove();
- sleep 1

FB.XFBML.parse(document.getElementById('page_#{ @blogs.current_page }'));

app/views/blogs/new.html.haml
%section.admin
  %h1 new blog entry
  = render 'form'

app/views/blogs/show.html.haml
=render partial: 'blogs/blog', locals: { blog: @blog }

#fb-root
:javascript
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2
        = pluralize(@user.errors.count, 'error')
        prohibited this user from being saved:
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :password, 'Password'
    = f.password_field :password
  .field
    = f.label :password_confirmation, 'Confirm'
    = f.password_field :password_confirmation
  .actions
    = f.submit

app/views/users/edit.html.haml
%section.admin
  %h1 edit user
  = render 'form'

app/views/users/index.html.haml
%section.admin
  %h1 listing users
  %table.admintable
    %thead
      %tr
        %th Name
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td.actions
            = link_to 'Edit', edit_user_path(user)
            = link_to 'Destroy', user, method: :delete, class: 'delete_btn', data: {confirm: 'Are you sure?', remote: true}
  = link_to 'New User', new_user_path, class: 'btn'

app/views/users/new.html.haml
%section.admin
  %h1 new user
  = render 'form'

app/views/users/show.html.haml
%section.admin
	%p
	  %b Name: 
	  = @user.name
	%p
	  %b Password digest: 
	  = @user.password_digest
	= link_to 'Edit', edit_user_path(@user)