config/routes.rb
JerkTest::Application.routes.draw do

  resources :menu_links


  root to: 'blogs#index'

  get 'admin' => 'admin#index'
  get 'contact' => 'static#contact'
  get 'test' => 'static#test'

  get 'pl' => 'pricelist#index'

  resources :users, :blogs, :blog_images
  
  resources :media, except: :show

  resources :artworks do
    collection{ post :sort }
  end

  resources :categories do
    collection{ post :sort }
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :category
 
  attr_accessible :img_url, :length, :medium, :title, :width, :year, :category_id, :sold, :price
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessible :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  validates :title, :medium, :img_url, :category_id, presence: true

  mount_uploader :img_url, UpjerkUploader

  def crop_avatar
    img_url.recreate_versions! if crop_x.present?
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  scope :descposted, order("blogs.posted DESC")


  attr_accessible :image, :post, :title, :posted

  validates :title, :image, presence: true

  belongs_to :user

  mount_uploader :image, UpjerkblogUploader
  
  self.per_page = 5

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :hidden, :name

  validates :name, presence: true

  has_many :artworks

  before_destroy :ensure_category_has_no_artwork

  private
  
  def ensure_category_has_no_artwork
  	if artworks.empty?
  		return true 
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end
  end

end

app/models/medium.rb
class Medium < ActiveRecord::Base
  attr_accessible :name
end

app/models/menu_link.rb
class MenuLink < ActiveRecord::Base
  attr_accessible :title, :url, :show
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  
  validates :name, presence: true, uniqueness: true
  
  has_secure_password
  
  has_many :blogs
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]

  def index
    @blogs = Blog.descposted.page(params[:page])
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.js { render nothing: true }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    "current" if current_page?(path)
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/menu_links_helper.rb
module MenuLinksHelper
end

app/helpers/pricelist_helper.rb
module PricelistHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.haml
%section.admin
  %h1 Welcome
  %h2 Add Content
  %ul
    %li= link_to 'Blog Entry', new_blog_path
    %li= link_to 'New Artwork', new_artwork_path
    %li= link_to 'New Category', new_category_path
  %h2 Manage Content
  %ul
    %li= link_to 'Blog', blogs_path
    %li= link_to 'Artwork', artworks_path
    %li= link_to 'Categories', categories_path
  %h2 Settings
  %ul
    %li= link_to 'Users', users_path
  %a.logout= link_to 'Logout', logout_path, method: :delete

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Jerkface NYC
    %meta{ name: 'viewport', content: 'initial-scale=.95, user-scalable=no' }
    %link{ href: 'http://fonts.googleapis.com/css?family=Pontano+Sans', rel: 'stylesheet', type: 'text/css' }
    = stylesheet_link_tag    "application", media: 'all'
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      %header.main
        %h1 Jerkface
        %nav.main
          %input#showmenu{ type: 'checkbox', role: 'button' }
          %label.showmenu{ for: 'showmenu'}
            %svg{ xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 64 64' }
              %rect.iconline1{ x: '0', y: '16', width: '64', height: '8' }
              %rect.iconline2{ x: '0', y: '30', width: '64', height: '8' }
              %rect.iconline3{ x: '0', y: '44', width: '64', height: '8' }
          %ul
            %li= link_to 'Blog', root_path, class: cp(root_path)
            = render '/categories/categories'
            = render '/menu_links/menulinks'
            %li= link_to 'Contact', contact_path, class: cp(contact_path)
        - if session[:user_id]
          %nav.admin
            %input#showadmin{ type: 'checkbox', role: 'button' }
            %label.showmenu{ for: 'showadmin'}
              %svg{ xmlns: 'http://www.w3.org/2000/svg', viewBox: '0 0 200 200' }
                %path{ d: 'M166.365,76.239c-2.889-8.056-7.262-15.598-12.958-22.217l13.714-23.962l-40.81-23.357l-13.714,23.962 c-8.597-1.561-17.311-1.509-25.72,0.08L72.993,6.9L32.356,30.572L46.24,54.417c-2.743,3.232-5.263,6.723-7.453,10.549 c-2.184,3.816-3.918,7.757-5.321,11.769L5.874,76.841l0.173,47.029l27.598-0.104c2.883,8.065,7.253,15.592,12.953,22.215 l-13.714,23.961l40.81,23.357l13.714-23.962c8.592,1.558,17.305,1.519,25.71-0.086l13.889,23.849l40.637-23.671l-13.885-23.833 c2.743-3.246,5.274-6.743,7.458-10.559c2.19-3.826,3.918-7.771,5.326-11.779l27.582-0.099l-0.173-47.029L166.365,76.239z M141.081,123.512c-12.985,22.688-41.905,30.554-64.593,17.569S45.934,99.176,58.919,76.488s41.905-30.554,64.593-17.569 S154.066,100.824,141.081,123.512z' }
            %ul
              %li
                %ul
                  .navTitle Add
                  %li= link_to 'Blog Entry', new_blog_path
                  %li= link_to 'Artwork', new_artwork_path
                  %li= link_to 'Category', new_category_path
              %li 
                %ul
                  .navTitle Manage
                  %li= link_to 'Blog', blogs_path
                  %li= link_to 'Artworks', artworks_path
                  %li= link_to 'Categories', categories_path
                  %li= link_to 'Menu Links', menu_links_path
              %li
                %ul
                  .navTitle Settings
                  %li= link_to 'Users', users_path
              %li.logout= link_to 'Logout', logout_path, method: :delete 
      .content
        - if notice
          %p#notice= notice
        = yield

      