config/routes.rb
JerkTest::Application.routes.draw do

  resources :menu_links


  root to: 'blogs#index'

  get 'admin' => 'admin#index'
  get 'contact' => 'static#contact'
  get 'test' => 'static#test'

  get 'pl' => 'pricelist#index'

  resources :users, :blogs, :blog_images
  
  resources :media, except: :show

  resources :artworks do
    collection{ post :sort }
  end

  resources :categories do
    collection{ post :sort }
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
end

app/models/artwork.rb
class Artwork < ActiveRecord::Base
  belongs_to :category
 
  attr_accessible :img_url, :length, :medium, :title, :width, :year, :category_id, :sold, :price
  
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  attr_accessible :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  validates :title, :medium, :img_url, :category_id, presence: true

  mount_uploader :img_url, UpjerkUploader

  def crop_avatar
    img_url.recreate_versions! if crop_x.present?
  end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  scope :descposted, order("blogs.posted DESC")


  attr_accessible :image, :post, :title, :posted

  validates :title, :image, presence: true

  belongs_to :user

  mount_uploader :image, UpjerkblogUploader
  
  self.per_page = 5

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :hidden, :name

  validates :name, presence: true

  has_many :artworks

  before_destroy :ensure_category_has_no_artwork

  private
  
  def ensure_category_has_no_artwork
  	if artworks.empty?
  		return true 
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end
  end

end

app/models/medium.rb
class Medium < ActiveRecord::Base
  attr_accessible :name
end

app/models/menu_link.rb
class MenuLink < ActiveRecord::Base
  attr_accessible :title, :url, :show
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  
  validates :name, presence: true, uniqueness: true
  
  has_secure_password
  
  has_many :blogs
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  def index
    if !params[:category_id]
      @artworks = Artwork.all
    else
      @artworks = Category.find(params[:category_id]).artworks.order("position")
    end
    @categories = Category.order("position")
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  def new
    @artwork = Artwork.new
  end

  def edit
    @artwork = Artwork.find(params[:id])
  end

  def create
    @artwork = Artwork.new(params[:artwork])
    if @artwork.save
      if params[:artwork][:img_url]
        render :crop
      else
        redirect_to artworks_path, notice: 'Artwork was successfully created.'
      end
    else
      render :new
    end
  end

  def update
    @artwork = Artwork.find(params[:id])
    if @artwork.update_attributes(params[:artwork])
      if params[:artwork][:img_url]
        render :crop
      else
        redirect_to artworks_path(category_id: @artwork.category.id), notice: 'Artwork was successfully updated.'
      end
    else
      render :edit
    end
  end

  def destroy
    @artwork = Artwork.find(params[:id])
    @artwork.destroy
    respond_to do |format|
      format.html { redirect_to artworks_url }
      format.js { render nothing: true }
    end
  end

  def sort
    params[:artwork].each_with_index do |id, index|
      Artwork.update_all({position: index+1}, {id: id})
    end
    render nothing: true
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_filter :authorize, only: [:index, :show]

  def index
    @blogs = Blog.descposted.page(params[:page])
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.js { render nothing: true }
    end
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
  def index
    @media = Medium.all
  end

  def new
    @medium = Medium.new
  end

  def edit
    @medium = Medium.find(params[:id])
  end

  def create
    @medium = Medium.new(params[:medium])

    respond_to do |format|
      if @medium.save
        format.html { redirect_to media_url, notice: 'Medium was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @medium = Medium.find(params[:id])

    respond_to do |format|
      if @medium.update_attributes(params[:medium])
        format.html { redirect_to @medium, notice: 'Medium was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @medium = Medium.find(params[:id])
    @medium.destroy

    respond_to do |format|
      format.html { redirect_to media_url }
      format.js { render nothing: true}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html
    end
  end

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created." }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully updated." }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.js { render nothing: true }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def cp(path)
    "current" if current_page?(path)
  end
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/menu_links_helper.rb
module MenuLinksHelper
end

app/helpers/pricelist_helper.rb
module PricelistHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artworks/_form.html.haml
= form_for(@artwork) do |f|
  - if @artwork.errors.any?
    #error_explanation
      %h2
        = pluralize(@artwork.errors.count, "error")
        prohibited this artwork from being saved:
      %ul
        - @artwork.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :category_id
    = f.collection_select(:category_id, Category.all, :id, :name, { selected: params[:category_id] })
  .field
    = f.label :price
    = f.number_field :price
  .field
    = f.label :sold
    = f.check_box :sold
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :medium
    = f.text_field :medium, value: 'Acrylic on Canvas', id: 'mediumtxt', data: {auto_complete_source: @media }
  .field
    = f.label :width
    = f.number_field :width
  .field
    = f.label :length
    = f.number_field :length
  .field
    = f.label :year, class: 'grid_1 alpha'
    = f.select :year, (2000..Time.now.year).to_a.reverse, { prompt: false }
  .field
    = f.label :img_url
    = f.file_field :img_url
  .actions
    = f.submit

app/views/artworks/crop.html.haml
%section.admin
  %h1 create thumbnail


  = form_for @artwork do |f|
    - %w[x y w h].each do |attribute|
      = f.hidden_field 'crop_' + attribute

    .actions
      = f.submit 'Crop'

  %br
  
  #cropbox= image_tag @artwork.img_url_url(:large)
  / #crop-preview{ style: 'width:180px; height:180px; overflow:hidden' }
  /   #preview= image_tag @artwork.img_url_url(:large)

app/views/artworks/edit.html.haml
%section.admin
  %h1 edit artwork
  = render 'form'

app/views/artworks/index.html.haml
%section.admin
  %h1 listing artworks

  %ul#categoryselectlist
    - @categories.each do |category|
      %li
        %a{ href: artworks_path(category_id: category.id), class: cp(artworks_path(category_id: category.id)) }=category.name

  %table.admintable
    %thead
      %tr
        %th
        %th Title
        %th Price
        %th Medium
        %th Size
        %th Year
        %th
    %tbody.sorts{ data: { update_url: sort_artworks_url } }
      - @artworks.each do |artwork|
        = content_tag_for :tr, artwork do
          %td= image_tag artwork.img_url_url(:icon).to_s
          %td
            = raw "<span class='sold'>&bull;</span>" if artwork.sold
            = link_to artwork.title, artwork
          %td $#{artwork.price}
          %td= artwork.medium
          %td= artwork.width.to_s + " x " +artwork.length.to_s
          %td= artwork.year
          %td.actions
            = link_to 'Edit', edit_artwork_path(artwork, category_id: params[:category_id])
            = link_to 'Destroy', artwork, method: :delete, class: 'delete_btn', data: { confirm: 'Are you sure?', remote: true }

  = link_to 'New Artwork', new_artwork_path(category_id: params[:category_id]), class: 'btn'

app/views/artworks/new.html.haml
%section.admin
  %h1 new artwork
  = render 'form'

app/views/artworks/show.html.haml
%section.admin
	%img{ src: @artwork.img_url_url(:thumb).to_s }
	%p= @artwork.title
	%p= @artwork.medium 
	%p= @artwork.length.to_s + " x " + @artwork.width.to_s
	%p= @artwork.year